version: 2

sources:
  - name: bronze
    schema: bronze
    freshness:
      warn_after: {count: 24, period: hour}
      error_after: {count: 48, period: hour}
    loaded_at_field: "_loaded_at"
    tables:
      - name: rt_details
      - name: rt_score
      - name: rt_reviews
      - name: rt_critic_reviews
      - name: rt_crosswalk
      - name: mc_general
      - name: mc_critic_reviews
      - name: mc_user_reviews
