version: 2

sources:
  - name: bronze
    schema: bronze
    tables:
      - name: rt_details
      - name: rt_score
      - name: rt_reviews
      - name: rt_critic_reviews
      - name: rt_crosswalk
      - name: mc_general
      - name: mc_critic_reviews
      - name: mc_user_reviews
